---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  namespace: default
  labels:
    app: order-deployment
spec:
  selector:
    matchLabels:
      app: order-deployment
  template:
    metadata:
      labels:
        app: order-deployment
    spec:
      containers:
        - name: order-service
          image: asia-southeast2-docker.pkg.dev/multiwarehouse-449808/com-multiwarehouse-app-repository/order.service:1.0-SNAPSHOT
          imagePullPolicy: Always
          env:
            - name: XENDIT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: XENDIT_SECRET
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: ORDER_DB_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: SPRING_DATASOURCE_PASSWORD
            - name: KAFKA-CONFIG_BOOTSTRAP-SERVERS
              value: "gke-confluent-kafka-cp-kafka-headless:9092"
            - name: KAFKA-CONFIG_SCHEMA-REGISTRY-URL
              value: "http://gke-confluent-kafka-cp-schema-registry:8081"
          resources:
            limits:
              cpu: "500m"
              memory: "1024Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: default
  labels:
    app: order-service
spec:
  selector:
    app: order-deployment
  ports:
    - name: order-service-port
      protocol: TCP
      port: 8182
  type: LoadBalancer
  loadBalancerIP: "34.128.116.196"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: warehouse-deployment
  namespace: default
  labels:
    app: warehouse-deployment
spec:
  selector:
    matchLabels:
      app: warehouse-deployment
  template:
    metadata:
      labels:
        app: warehouse-deployment
    spec:
      containers:
        - name: warehouse-service
          image: asia-southeast2-docker.pkg.dev/multiwarehouse-449808/com-multiwarehouse-app-repository/warehouse.service:1.0-SNAPSHOT
          imagePullPolicy: Always
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: WAREHOUSE_DB_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: SPRING_DATASOURCE_PASSWORD
            - name: KAFKA-CONFIG_BOOTSTRAP-SERVERS
              value: "gke-confluent-kafka-cp-kafka-headless:9092"
            - name: KAFKA-CONFIG_SCHEMA-REGISTRY-URL
              value: "http://gke-confluent-kafka-cp-schema-registry:8081"
          resources:
            limits:
              cpu: "500m"
              memory: "1024Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: warehouse-service
  namespace: default
  labels:
    app: warehouse-service
spec:
  selector:
    app: warehouse-deployment
  ports:
    - name: warehouse-service-port
      protocol: TCP
      port: 8181
  type: LoadBalancer
  loadBalancerIP: "34.128.116.196"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  namespace: default
  labels:
    app: user-deployment
spec:
  selector:
    matchLabels:
      app: user-deployment
  template:
    metadata:
      labels:
        app: user-deployment
    spec:
      containers:
        - name: user-service
          image: asia-southeast2-docker.pkg.dev/multiwarehouse-449808/com-multiwarehouse-app-repository/user.service:1.0-SNAPSHOT
          imagePullPolicy: Always
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: USER_DB_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: SPRING_DATASOURCE_PASSWORD
            - name: KAFKA-CONFIG_BOOTSTRAP-SERVERS
              value: "gke-confluent-kafka-cp-kafka-headless:9092"
            - name: KAFKA-CONFIG_SCHEMA-REGISTRY-URL
              value: "http://gke-confluent-kafka-cp-schema-registry:8081"
          resources:
            limits:
              cpu: "500m"
              memory: "1024Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: default
  labels:
    app: user-service
spec:
  selector:
    app: user-deployment
  ports:
    - name: user-service-port
      protocol: TCP
      port: 8183
  type: LoadBalancer
  loadBalancerIP: "34.128.116.196"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
  namespace: default
  labels:
    app: product-deployment
spec:
  selector:
    matchLabels:
      app: product-deployment
  template:
    metadata:
      labels:
        app: product-deployment
    spec:
      containers:
        - name: product-service
          image: asia-southeast2-docker.pkg.dev/multiwarehouse-449808/com-multiwarehouse-app-repository/product.service:1.0-SNAPSHOT
          imagePullPolicy: Always
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: PRODUCT_DB_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: SPRING_DATASOURCE_PASSWORD
            - name: KAFKA-CONFIG_BOOTSTRAP-SERVERS
              value: "gke-confluent-kafka-cp-kafka-headless:9092"
            - name: KAFKA-CONFIG_SCHEMA-REGISTRY-URL
              value: "http://gke-confluent-kafka-cp-schema-registry:8081"
          resources:
            limits:
              cpu: "500m"
              memory: "1024Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: default
  labels:
    app: product-service
spec:
  selector:
    app: product-deployment
  ports:
    - name: product-service-port
      protocol: TCP
      port: 8185
  type: LoadBalancer
  loadBalancerIP: "34.128.116.196"